function Hd = filtrohamming
%FILTROHAMMING Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 27-Apr-2026 20:34:41

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 300;  % Sampling Frequency

N    = 10;       % Order
Fc   = 15;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
